name: fraud-detection-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - scikit-learn=1.4.0
  - pandas=2.1.0
  - numpy=1.24.0
  - mlflow=2.3.0
  - pip:
    - boto3
    - requests  
